### ISSUE TITLE
iOS 14 & XCode 12 - not snapshotting content

### ISSUE THREAD

**Issue by Kaspik** [SebastianOsinski/TableViewCellSnapshotTesting#1]
Hey! We have been using this approach for months with success, but It doesn't work on iOS 14 / XCode 12. I can't seem to find any reason why it's like that, and I was wondering if you tested this already on the new system?

The result snapshots are just blank images.

**Comment by Kaspik** [comment]
@SebastianOsinski Any idea please? :)

**Comment by navartis** [comment]
@Kaspik Are you using contentView in your cells?

**Comment by Kaspik** [comment]
Of course we are! :)

**Comment by Kaspik** [comment]
Does everything work for you on iOS 14 @navartis ? We are still experiencing this after months....

**Comment by navartis** [comment]
@Kaspik Everything works fine even with Xcode 12.4 and iOS Simulator 14.4. 

I'm adopt a bit TableViewCellSnapshotContainer.swift for our own project UIKit with specified Cells registration and dequeuing mechanism.

We have a lot of tests with **51 311** reference snapshots.

**Comment by Kaspik** [comment]
@navartis Would you mind sharing your implementation please?

**Comment by navartis** [comment]
@Kaspik You are welcome: https://github.com/SebastianOsinski/TableViewCellSnapshotTesting/pull/2

You should explore request commit by commit for understand what you should do in project.

**Comment by Kaspik** [comment]
Thank you!

We do not use FBSnapshotting but swift-snapshot-testing and I had almost everything configured correctly - but it lead me to an issue with the snapshot library rendering cells and I was able to fix it, thanks!
